config/routes.rb
Rails.application.routes.draw do


  resources :emergencies
  resources :testimonials
  root 'static_pages#welcome'

  localized do
    get 'calendar/(:date)', to: 'calendar#work_calendar', as: "work_calendar"
    get 'work_day_calendar/(:date)', to: 'calendar#work_day_calendar', as: "work_day_calendar"
    get '/newhome', to: 'static_pages#newhome', as: "newhome"
    get '/about', to: 'static_pages#about', as: "about"
    get '/faq', to: 'static_pages#faq', as: "faq"
    get '/contact', to: 'static_pages#contact', as: "contact"


    get '/internship', to: 'static_pages#internship', as: "internship"
    # get '/testimonials', to: 'static_pages#testimonials', as: "testimonials"
    get '/support', to: 'static_pages#support', as: "support"
    get '/privacy_statement', to: 'static_pages#privacy_statement', as: "privacy_statement"


    #get '/contact', to: 'pages#show', as: "contact", id: "kontakt"
    #get '/support', to: 'pages#show', as: "support", id: "unterstuetzen"
  end

  #save_the_chicken
  localized do
    scope "/save_the_chicken" do
      get '/', to: 'save_the_chicken#welcome', as: "save_the_chicken"
      get '/faq', to: 'save_the_chicken#faq', as: "save_the_chicken_faq"
      get '/contact', to: 'save_the_chicken#contact', as: "save_the_chicken_contact"
      get '/keeping', to: 'save_the_chicken#keeping', as: "save_the_chicken_keeping"
      get '/act_sustainable', to: 'save_the_chicken#act_sustainable', as: "save_the_chicken_act_sustainable"
      get '/new_home', to: 'save_the_chicken#new_home', as: "save_the_chicken_new_home"
      get '/donation', to: 'save_the_chicken#donation', as: "save_the_chicken_donation"
      get '/picture_gallery', to: 'save_the_chicken#picture_gallery', as: "save_the_chicken_picture_gallery"
      get '/requirements', to: 'save_the_chicken#requirements', as: "save_the_chicken_requirements"
    end
  end

  post '/save_the_chicken/create_for_adopters', to: "chicken_adoptions#create_for_adopters", as: "create_for_adopters"
  get '/save_the_chicken/successfully_added_chicken_adoption', to: "chicken_adoptions#successfully_added_chicken_adoption", as: "successfully_added_chicken_adoption"

  get 'home_offers/successfully_added_home_offer', to: 'home_offers#successfully_added_home_offer', as: "successfully_added_home_offer"
  get 'home_requests/successfully_added_home_request', to: 'home_requests#successfully_added_home_request', as: "successfully_added_home_request"

  get '/impressum', to: 'static_pages#impressum', as: "impressum"
  get '/cookies', to: 'static_pages#cookies', as: "cookies"

  post '/works/create_for_calendar/', to: "works#create_for_calendar", as: 'create_for_calendar'
  delete '/works/delete_for_calendar/:id', to: "works#delete_for_calendar", as: 'delete_for_calendar'

  #sponsorship
  get '/sponsorships/my_sponsorships', to: "sponsorships#my_sponsorships", as: 'my_sponsorships'
  post '/sponsorships/add_sponsorship', to: "sponsorships#add_sponsorship", as: 'add_sponsorship'
  post '/sponsorships/add_sponsorship_with_new_user', to: "sponsorships#add_sponsorship_with_new_user", as: 'add_sponsorship_with_new_user'
  get '/sponsorships/activate_sponsorship/:id', to: "sponsorships#activate_sponsorship", as: 'activate_sponsorship'
  get '/sponsorships/deactivate_sponsorship/:id', to: "sponsorships#deactivate_sponsorship", as: 'deactivate_sponsorship'
  post '/sponsorships/check_payment/:id', to: "sponsorships#check_payment", as: 'check_payment'
  post '/sponsorships/add_sponsorship_without_sending_mail', to: "sponsorships#add_sponsorship_without_sending_mail", as: 'add_sponsorship_without_sending_mail'

  post '/home_requests/archive/:id', to: "home_requests#archive", as: "archive_home_request"
  post '/home_offers/archive/:id', to: "home_offers#archive", as: "archive_home_offer"
  get '/home_offers/matches_for_home_offer', to: "home_offers#matches_for_home_offer", as: "matches_for_home_offer"
  get '/home_offers/compare/:home_offer_id/:home_request_id', to: "home_offers#compare", as: "home_offers_compare"
  get '/home_requests/compare/:home_request_id/:home_offer_id', to: "home_requests#compare", as: "home_requests_compare"

  #search
  get 'animals/search_animals', to: 'animals#search_animals', as: 'search_animals'
  get 'home_offers/search_home_offers', to: 'home_offers#search_home_offers', as: 'search_home_offers'
  get 'home_requests/search_home_requests', to: 'home_requests#search_home_requests', as: 'search_home_requests'
  get 'sponsorships/search_sponsorships', to: 'sponsorships#search_sponsorships', as: 'search_sponsorships'

  #animals
  get 'animals/animal_in_need_of_sponsorship', to: 'animals#animal_in_need_of_sponsorship', as: 'animal_in_need_of_sponsorship'

  #admin
  get 'admin/visits', to: 'admin#visits', as: "visits"
  get 'admin/user_overview', to: 'admin#user_overview', as: "user_overview"
  post '/admin/create_user', to: 'admin#create_user', as: "create_user"
  delete '/admin/delete_user/:user_id', to: 'admin#delete_user', as: "delete_user"

  #offerer
  get '/offerers/process_to_create_home_offer', to: 'offerers#process_to_create_home_offer', as: "process_to_create_home_offer"
  post '/add_offerer', to: "offerers#add_offerer", as: 'add_offerer'

  #home_offer
  post 'home_offers/add_home_offer_to_offerer', to: "home_offers#add_home_offer_to_offerer", as: 'add_home_offer_to_offerer'

  #chicken_adoptions
  get 'chicken_adoptions/search_chicken_adoptions', to: 'chicken_adoptions#search_chicken_adoptions', as: 'search_chicken_adoptions'
  post '/chicken_adoptions/archive/:id', to: "chicken_adoptions#archive", as: "archive_chicken_adoption"

  #redirects
  #get '/team', to: redirect('/team_members')

  #newsletters
  post '/newsletters/add_newsletter_to_list', to: "newsletters#add_newsletter_to_list", as: "add_newsletter_to_list"

  #download custom files
  get "/download_vermittlungsbedingungen", to: 'home_requests#download_vermittlungsbedingungen', as: 'download_vermittlungsbedingungen'


  devise_for :users
  localized do
    resources :team_members
    resources :posts
    resources :home_requests
    resources :home_offers
    resources :animals
    resources :works
    resources :sponsorships
    resources :offerers
    resources :chicken_adoptions
    resources :newsletters
    resources :events
    resources :pages
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!, only: [:visits]
  before_action :is_user_allowed?, only: [:visits]

  include ApplicationHelper

  def welcome
    set_meta_tags title: 'Herzlich Wilkommen', reverse: true,
              description: 'Die Stiftung "Tiere in Not - Animal Help" engagiert sich seit Jahren sowohl im institutionellen als auch im individuellen Tierschutz.',
              keywords: 'Tierschutz, Tierrechte, Tiere in Not, Hilfe für Tiere, Animal Help, Lebenshof, Gnadenhof',
              og: {
                title: :title,
                url: root_url,
                image: ActionController::Base.helpers.asset_url("main-picture.jpeg", type: :image)
              }

    #@posts = Post.all.order("created_at").reverse_order.first(5)
    #@events = Event.where("start > ?", DateTime.now).order("start")
  end

  def newhome
    set_meta_tags title: 'Tiervermittlung', reverse: true,
              description: 'Stinah versucht für Tiere, die sich in Notsituationen befinden, ein neues Zuhause zu finden. Sie können einem Tier ein neues Zuhause bieten? Wir freuen uns über Ihre Kontaktaufnahme!',
              keywords: 'Tiervermittlung, Ich suche ein neues Zuhause für mein Tier, Ich biete einem Tier ein neues Zuhause'
  end

  def about

    @page = Page.where(slug: "über-stinah")

    @page = @page.first if @page.any?

    unless @page.blank?
      set_meta_tags title: @page.title, reverse: true,
            description: @page.description,
            keywords: @page.keywords
    end
    #set_meta_tags title: 'Über STINAH', reverse: true,
    #          description: 'Die Stiftung "Tiere in Not - Animal Help" hat es sich zur Aufgabe gemacht, die Umsetzung des verfassungsrechtlich verankerten Schutzes der Würde
    #                        der Kreatur voranzutreiben, die Stellung des Tieres als Mitgeschöpf zu festigen und als Konsequenz aus den ersten beiden Aufgaben die Tiere vor Ausbeutung
    #                        und Missbrauch zu schützen und ihnen - wo immer nötig – beizustehen.',
    #          keywords: 'Stinah, Stiftung Tiere in Not Animal Help'
  end

  def faq
    @page = Page.where(slug: "faq")

    @page = @page.first if @page.any?

    unless @page.blank?
      set_meta_tags title: @page.title, reverse: true,
            description: @page.description,
            keywords: @page.keywords
    end

    #set_meta_tags title: 'FAQ', reverse: true,
    #          description: 'Antworten auf die häufigsten gestellten Fragen.'
  end

  def internship
    @testimonials = Testimonial.where(category: "interns")

    set_meta_tags title: 'Praktikum bei Stinah', reverse: true,
              description: 'Ein Praktikum bei Stinah machen! Wohnung ist im Praktikum inklusive.',
              keywords: "Praktikum bei Stinah, Tierschutzarbeit"
  end

  def contact

    @page = Page.where(slug: "kontakt")

    @page = @page.first if @page.any?

    unless @page.blank?
      set_meta_tags title: @page.title, reverse: true,
            description: @page.description,
            keywords: @page.keywords
    end

    #set_meta_tags title: 'Kontakt', reverse: true,
    #          description: 'Hier können Sie Kontakt mit der Stinah aufnehmen.'
  end

  def testimonials
    set_meta_tags title: 'Erfahrungsberichte', reverse: true,
              description: 'Praktikum? Auf einem Lebenshof arbeiten? Tierschutzarbeit? Die Erfahrungsberichte.'
  end

  def support
    @page = Page.where(slug: "unterstützen")

    @page = @page.first if @page.any?

    unless @page.blank?
      set_meta_tags title: @page.title, reverse: true,
            description: @page.description,
            keywords: @page.keywords
    end

    #set_meta_tags title: 'Stinah unterstützen!', reverse: true,
    #          description: 'Mit einer Spende helfen Sie der Stiftung, ihren täglichen Einsatz zugunsten der Tiere zu finanzieren.',
    #          keywords: "Spende, Patenschaft, Tierschutz, Gönnerbeitrag, Naturalspende"


  end

  def impressum
    set_meta_tags title: 'Impressum', reverse: true
  end

  def cookies
    set_meta_tags title: 'Cookies', reverse: true
  end

  def privacy_statement
    set_meta_tags title: 'Datenschutzerklärung', reverse: true
  end

  private

  def is_user_allowed?
    if !is_current_user_admin?
      #raise "not authorized"
      sign_out current_user
      flash[:notice] = "Sie sind nicht authorisiert!"
      redirect_to root_path
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_donation_info_card.html.erb
<div class="card bg-light no-gutters mb-3 b-color rounded-0">
  <div class="card-body b-color text-center" style="padding-top: 0px;">
    <p class="text-center">
      <div class="info-card-icon text-center">
            <%= inline_svg_tag "icon_spenden_sz.svg", class: '' %>
        </div>
    </p>
    <h4 class="spaced-letters text-a-color">
      <strong>
        <%= "Spenden".upcase %>
      </strong>
    </h4>
    <p>
      <%= link_to root_path do %>
        <button type="button" class="mt-3 btn btn-e-color btn-sm spaced-letters text-nowrap rounded-0"><strong>MEHR ERFAHREN</strong> <%= fa_icon "chevron-right", class: "ml-2" %></button>
      <% end %>
    </p>
  </div>
</div>

app/views/static_pages/_info-cards.html.erb
<div class="container-fluid f-color pt-5">
  <div class="container">
    <h5 class="spaced-letters text-white mb-4"><%= "Wie Sie uns auch noch unterstützen können".upcase %></h5>

    <div class="card-deck">
      <%= render "static_pages/donation_info_card" %>
      <%= render "static_pages/internship_info_card" %>
      <%= render "static_pages/work_info_card" %>
    </div>
  </div>
</div>

app/views/static_pages/_info_card.html.erb
<div class="card rounded-0 text-white">
  <%= image_tag("goat.png", class: "card-img") %>
  <div class="card-img-overlay overlay-dark d-flex flex-column justify-content-center">
      <p class="card-text text-center spaced-letters"><small><%= "Bei uns leben unter anderem".upcase %></small></p>
      <h4 class="card-title text-center spaced-letters mt-n3"><strong><%= "11 Kühe und Ochsen".upcase %></strong></h4>
    <p class="card-text text-center mt-3">
      <%= link_to root_path do %>
        <button type="button" class="btn btn-c-color btn-sm spaced-letters text-nowrap rounded-0">MEHR ERFAHREN <%= fa_icon "chevron-right", class: "ml-2" %></button>
      <% end %>
    </p>
  </div>
</div>

app/views/static_pages/_internship_info_card.html.erb
<div class="card bg-light no-gutters mb-3 b-color rounded-0">
  <div class="card-body b-color text-center" style="padding-top: 0px;">
    <p class="text-center">
      <div class="info-card-icon text-center">
            <%= inline_svg_tag "icon_praktikum_sz.svg", class: '' %>
        </div>
    </p>
    <h5 class="spaced-letters text-a-color">
      <strong>
        <%= "Praktikum".upcase %>
      </strong>
    </h5>
    <p>
      <%= link_to root_path do %>
        <button type="button" class="mt-3 btn btn-e-color btn-sm spaced-letters text-nowrap rounded-0"><strong>MEHR ERFAHREN</strong> <%= fa_icon "chevron-right", class: "ml-2" %></button>
      <% end %>
    </p>
  </div>
</div>

app/views/static_pages/_patenschaft.html.erb
<div class="container-fluid a-color d-none d-md-block" style="background-size: cover; background-repeat: no-repeat; background-image: url('<%= image_url("man-holding-horse-face.jpg") %>'); background-position: center; height: 600px;">
  <div class="row justify-content-center">
    <div class="col-md-4 offset-md-6 col-sm-6 offset-sm-4 mt-5">
        <h2 class="text-white spaced-letters"><strong><%= "Patenschaft".upcase %></strong></h2>
        <br />
        <p class="lead">
          <strong>
            Mit einer Patenschaft helfen Sie, einzelnen Tieren Zuflucht zu bieten
            und ihnen ein gesichertes Dasein zu gewährleisten.
          </strong>
        </p>
        <br />
        <p>
          Ermöglichen Sie mit diesem tierschützerischen Beitrag einem Mitlebewesen ein artgerechtes Leben.
          Ein solches Tier übernimmt immer auch die Funktion einer Botschafterin / eines Botschafters und vermittelt den Wert des Wesens an sich.
        </p>
        <p class="mt-5">
          <%= link_to root_path do %>
            <button type="button" class="btn btn-c-color spaced-letters text-nowrap rounded-0"><%= "Jetzt Patin / Pate werden".upcase %> <%= fa_icon "chevron-right", class: "ml-2" %></button>
          <% end %>
        </p>
      </div>
    </div>
  </div>

  <div class="container-fluid a-color d-block d-md-none p-4">
    <h2 class="text-white spaced-letters"><strong><%= "Patenschaft".upcase %></strong></h2>
    <br />
    <p class="lead">
      <strong>
        Mit einer Patenschaft helfen Sie, einzelnen Tieren Zuflucht zu bieten
        und ihnen ein gesichertes Dasein zu gewährleisten.
      </strong>
    </p>
    <br />
    <p>
      Ermöglichen Sie mit diesem tierschützerischen Beitrag einem Mitlebewesen ein artgerechtes Leben.
      Ein solches Tier übernimmt immer auch die Funktion einer Botschafterin / eines Botschafters und vermittelt den Wert des Wesens an sich.
    </p>
    <p class="mt-5">
      <%= link_to root_path do %>
        <button type="button" class="btn btn-c-color spaced-letters text-nowrap rounded-0"><%= "Jetzt Patin / Pate werden".upcase %> <%= fa_icon "chevron-right", class: "ml-2" %></button>
      <% end %>
    </p>
  </div>

<div class="container-fluid a-color d-block d-md-none" style="background-size: cover; background-repeat: no-repeat; background-image: url('<%= image_url("man-holding-horse-face.jpg") %>'); background-position: center; height: 600px;">

</div>

app/views/static_pages/_work_info_card.html.erb
<div class="card bg-light no-gutters mb-3 b-color rounded-0">
  <div class="card-body b-color text-center" style="padding-top: 0px;">
    <p class="text-center">
      <div class="info-card-icon text-center">
          <%= inline_svg_tag "icon_arbeitseinsatz_sz.svg", class: '' %>
      </div>
    </p>
    <p class="spaced-letters text-a-color">
      <strong>
        <%= "Natural- / Zeitspende".upcase %>
      </strong>
    </p>
    <p>
      <%= link_to root_path do %>
        <button type="button" class="mt-3 btn btn-e-color btn-sm spaced-letters text-nowrap rounded-0"><strong>MEHR ERFAHREN</strong> <%= fa_icon "chevron-right", class: "ml-2" %></button>
      <% end %>
    </p>
  </div>
</div>

app/views/static_pages/internship.html.erb
<div class="container">
  <div class="jumbotron bg-white my-4">
    <div class="text-center">
      <%= link_to root_path do %>
        <%= image_tag("stinah-logo.png", class: "img-fluid mb-4") %>
      <% end %>

      <h1 class="my-4 text-darker-base-color"><%= title %></h1>
    </div>
    <div class="text-justify text-darker-base-color">
<div id="cc-m-6930836386" dir="ltr">
	<p>Möchten Sie sich in Form von konkreter Tierschutzarbeit
	engagieren?&nbsp;<br/>
<br/>
Stinah bietet die Möglichkeit, im
	Rahmen von Praktikas (minimale Dauer 3 Monate) konkreten Einsatz für
	Tiere zu leisten und Erfahrungen in der Tierbetreuung (v.a. Pferde)
	zu sammeln. Unterkunft mit Küche/Dusche/WC vorhanden.<br/>
<br/>
Weitere
	Informationen bzw. Bewerbungen per <%= mail_to "info@stinah.ch", "info@stinah.ch", subject: "Praktikum bei Stinah", body: "Sehr geehrte Damen und Herren." %> oder
	unter 052 654 33 33.
	</p>
</div>

<% if is_current_user_admin? %>
  <div class="text-center">
    <%= link_to 'Neuer Eintrag', new_testimonial_path, class: "btn btn-primary my-2" %>
  </div>
<% end %>
<%= render partial: "testimonials/show", collection: @testimonials, as: :testimonial %>

    </div>
  </div>
</div>

app/views/static_pages/support.html.erb
  <% if @page.present? %>
    <%= render 'pages/show', page: @page %>
  <% else %>
    <p>
      Bitte Seite mit Slug "unterstützen" erstellen
    </p>
  <% end %>

app/views/static_pages/welcome-old.html.erb
<div class="container horse-enter-bg">

  <div class="text-center">
    <%= link_to root_path do %>
      <%= image_tag("stinah-logo.png", class: "img-fluid mb-4") %>
    <% end %>
  </div>

  <div class="jumbotron p-4 p-md-5 text-center rounded base-color">
    <div class="px-0">
      <h1 class="display-5">Herzlich Willkommen!</h1>
      <p class="lead">
        Hier finden Sie alle Informationen über die Stiftung <strong>Tiere in Not- Animal Help</strong>, ihre Tiere, ihre Zielsetzung und ihr Engagement.
      </p>
    </div>
  </div>


  <div class="my-4">

  </div>

  <%#= render "shared/news_images", posts: @posts %>
  <%#= render "posts/card_with_overlay", post: @posts.first %>

  <div class="row no-gutters">
    <div class="col-lg-6 col-md-12 mb-2 mb-lg-0 pr-lg-1">
      <div class="card h-100">
        <div class="hovereffect">
            <%= image_tag "pig_cute.png", class: "card-img h-100" %>
            <div class="card-img-overlay d-flex align-items-end">
              <h3 class="card-title text-white">Unsere Tiere</h3>
            </div>
            <div class="overlay">
               <h2>Unsere Tiere</h2>
               <%= link_to "Entdecken", animals_path, class: "info" %>
            </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6 col-md-12">
      <div class="row no-gutters">
        <div class="col-md-6 col-sm-12 mb-2 mb-md-0">
          <div class="card h-100">
            <div class="hovereffect">
                <%= image_tag "stiftungsgruender.png", class: "card-img h-100" %>
                <div class="card-img-overlay d-flex align-items-end">
                  <h3 class="card-title text-white">Über STINAH</h3>
                </div>
                <div class="overlay">
                   <h2>Über STINAH</h2>
                   <%= link_to "Mehr erfahren", about_path, class: "info" %>
                </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-sm-12 mb-2 mb-md-0">
          <div class="card h-100">
            <div class="hovereffect">
                <%= image_tag "chicken_free.jpg", class: "card-img h-100" %>
                <div class="card-img-overlay d-flex align-items-end">
                  <h3 class="card-title text-white">STINAH unterstützen!</h3>
                </div>
                <div class="overlay">
                   <h2>STINAH unterstützen!</h2>
                   <%= link_to "Mithelfen", support_path, class: "info" %>
                </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-sm-12 mb-2 mb-md-0">
          <div class="card h-100">
            <div class="hovereffect">
                <%= image_tag "cow.png", class: "card-img h-100" %>
                <div class="card-img-overlay d-flex align-items-end">
                  <h3 class="card-title text-white">Tier - Vermittlung</h3>
                </div>
                <div class="overlay">
                   <h2>Tiervermittlung</h2>
                   <%= link_to "Tiere abgeben oder aufnehmen", newhome_path, class: "info" %>
                </div>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-sm-12 mb-2 mb-md-0">
          <div class="card h-100">
            <div class="hovereffect">
                <%= image_tag "chicken_eating.jpeg", class: "card-img h-100" %>
                <div class="card-img-overlay d-flex align-items-end">
                  <h3 class="card-title text-white">Rettet das Huhn!</h3>
                </div>
                <div class="overlay">
                   <h2>Rettet das Huhn!</h2>
                   <%= link_to "Informieren", save_the_chicken_path, class: "info" %>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="my-4">

  </div>

  <%= render 'animals/animals_in_need_of_sponsorship' unless AnimalsSearch.new(search_inputs: {sponsorship_status: "without_sponsorship"}).search.empty? %>

  <div class="jumbotron p-4 p-md-5 text-center rounded base-color">
    <div class="px-0">
      <h1 class="display-5">Eine Patenschaft übernehmen!</h1>
      <p class="lead">
        Mit einer <strong>Patenschaft</strong> helfen Sie, einzelnen Tieren <strong>Zuflucht</strong> zu bieten und ihnen ein <strong>gesichertes Dasein</strong> zu gewährleisten.
      </p>
      <p class="lead">
        <%= link_to "Schau dir alle #{AnimalsSearch.new(sponsorship_status: "without_sponsorship").search.count} Tiere an, die deine Unterstützung brauchen!", animals_path(params: {search_inputs: {sponsorship_status: "without_sponsorship"}}), class:"btn btn-light btn-lg btn-block"  %>
      </p>
    </div>
  </div>

  <%= render 'newsletters/newsletter_box' %>
  <div class="my-4">

  </div>


</div>

app/views/static_pages/welcome.html.erb
<section class="horse-enter-bg">
    <div class="container d-flex align-items-end h-75">
      <div class="d-none d-md-block">
        <%= image_tag("logo_stinah_ws_vektor.png", class: "img-fluid mb-4", style: "height: 180px;") %>
      </div>
    </div>
</section>

<div class="container mb-3">
  <div class="row">
    <div class="col-md-4 col-sm-12">
      <div class="card text-white a-color mb-3 mt-n6 pb-2 p-2 rounded-0">
        <div class="card-body">
          <p class="spaced-letters text-light">
            <strong>HERZLICH WILLKOMMEN</strong>
            <hr align="left" width="10%" class="bg-light">
          </p>
          <p class="card-text">Die Stiftung Tiere in Not - Animal Help (Stinah) setzt sich dafür ein, dass die Stellung der Tiere als Mitlebewesen gefestigt wird. Auf unserem Lebenshof bieten wir über 100 Tieren einenPlatz, an dem sie vor Ausbeutung geschützt sind und ein Leben in Würde führen können.</p>
          <p class="card-text text-light">
            <strong>
              Für Ihr Interesse und Ihren Einsatz für Tiere danken wir Ihnen herzlich!
            </strong>
          </p>
        </div>
      </div>
      <%= image_tag("pig_cute.png", class: "img-fluid mt-n3") %>
    </div>

    <div class="col-md-8 col-sm-12 d-flex ">
      <div class="row">
      <div class="col-12 mb-5">
        <div class="mt-n7 p-2">
          <div class="float-right mr-5">
            <%= link_to support_path do %>
              <button type="button" class="btn c-color btn-circle btn-xl text-white spaced-letters">
                <strong>JETZT<br /> SPENDEN <br /></strong>
                <hr align="center" width="20px" class="bg-light">
              </button>
            <% end %>
          </div>
        </div>
      </div>
        <div class="align-self-end">
          <div class="col-12">
              <%= render "posts/horizontal_card", post: Post.last if Post.last.present? %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/welcome_old.html.erb
<div class="container">
  <div class="jumbotron bg-white my-4">
    <div class="text-center">
      <%= link_to root_path do %>
        <%= image_tag("stinah-logo.png", class: "img-fluid mb-4") %>
      <% end %>
      <h1 class="my-4 text-darker-base-color"><%= title %></h1>
      <p class="lead text-darker-base-color my-4">Hier finden Sie Informationen über die Stiftung, ihre Zielsetzung und ihr Engagement.</p>
      <p class="lead text-darker-base-color my-4">Für Ihr Interesse und Ihren Einsatz zugunsten der Tiere danken wir Ihnen herzlich!</p>
    </div>
    <%= render 'animals/animals_in_need_of_sponsorship' unless AnimalsSearch.new(search_inputs: {sponsorship_status: "without_sponsorship"}).search.empty? %>
    <br />
    <%= render "shared/welcome_thumbnail_carousel", image_names: ["cow.png", "chicken.png", "goat.png", "pig_cute.png", "three_horses.jpeg"] %>
</div>

  <div class="jumbotron bg-white my-4">
    <% if is_current_user_admin? %>
      <div class="text-center">
        <%= link_to 'Neuer Eintrag', new_post_path, class: "btn btn-primary" %>
      </div><hr />
    <% end %>
    <h1 class="text-center text-darker-base-color">Aktuell</h1>
    <%= render partial: "posts/show", collection: @posts, as: :post %>
  </div>

</div>