config/routes.rb
Rails.application.routes.draw do


  resources :emergencies
  resources :testimonials
  root 'static_pages#welcome'

  localized do
    get 'calendar/(:date)', to: 'calendar#work_calendar', as: "work_calendar"
    get 'work_day_calendar/(:date)', to: 'calendar#work_day_calendar', as: "work_day_calendar"
    get '/newhome', to: 'static_pages#newhome', as: "newhome"
    get '/about', to: 'static_pages#about', as: "about"
    get '/faq', to: 'static_pages#faq', as: "faq"
    get '/contact', to: 'static_pages#contact', as: "contact"


    get '/internship', to: 'static_pages#internship', as: "internship"
    # get '/testimonials', to: 'static_pages#testimonials', as: "testimonials"
    get '/support', to: 'static_pages#support', as: "support"
    get '/privacy_statement', to: 'static_pages#privacy_statement', as: "privacy_statement"


    #get '/contact', to: 'pages#show', as: "contact", id: "kontakt"
    #get '/support', to: 'pages#show', as: "support", id: "unterstuetzen"
  end

  #save_the_chicken
  localized do
    scope "/save_the_chicken" do
      get '/', to: 'save_the_chicken#welcome', as: "save_the_chicken"
      get '/faq', to: 'save_the_chicken#faq', as: "save_the_chicken_faq"
      get '/contact', to: 'save_the_chicken#contact', as: "save_the_chicken_contact"
      get '/keeping', to: 'save_the_chicken#keeping', as: "save_the_chicken_keeping"
      get '/act_sustainable', to: 'save_the_chicken#act_sustainable', as: "save_the_chicken_act_sustainable"
      get '/new_home', to: 'save_the_chicken#new_home', as: "save_the_chicken_new_home"
      get '/donation', to: 'save_the_chicken#donation', as: "save_the_chicken_donation"
      get '/picture_gallery', to: 'save_the_chicken#picture_gallery', as: "save_the_chicken_picture_gallery"
      get '/requirements', to: 'save_the_chicken#requirements', as: "save_the_chicken_requirements"
    end
  end

  post '/save_the_chicken/create_for_adopters', to: "chicken_adoptions#create_for_adopters", as: "create_for_adopters"
  get '/save_the_chicken/successfully_added_chicken_adoption', to: "chicken_adoptions#successfully_added_chicken_adoption", as: "successfully_added_chicken_adoption"

  get 'home_offers/successfully_added_home_offer', to: 'home_offers#successfully_added_home_offer', as: "successfully_added_home_offer"
  get 'home_requests/successfully_added_home_request', to: 'home_requests#successfully_added_home_request', as: "successfully_added_home_request"

  get '/impressum', to: 'static_pages#impressum', as: "impressum"
  get '/cookies', to: 'static_pages#cookies', as: "cookies"

  post '/works/create_for_calendar/', to: "works#create_for_calendar", as: 'create_for_calendar'
  delete '/works/delete_for_calendar/:id', to: "works#delete_for_calendar", as: 'delete_for_calendar'

  #sponsorship
  get '/sponsorships/my_sponsorships', to: "sponsorships#my_sponsorships", as: 'my_sponsorships'
  post '/sponsorships/add_sponsorship', to: "sponsorships#add_sponsorship", as: 'add_sponsorship'
  post '/sponsorships/add_sponsorship_with_new_user', to: "sponsorships#add_sponsorship_with_new_user", as: 'add_sponsorship_with_new_user'
  get '/sponsorships/activate_sponsorship/:id', to: "sponsorships#activate_sponsorship", as: 'activate_sponsorship'
  get '/sponsorships/deactivate_sponsorship/:id', to: "sponsorships#deactivate_sponsorship", as: 'deactivate_sponsorship'
  post '/sponsorships/check_payment/:id', to: "sponsorships#check_payment", as: 'check_payment'
  post '/sponsorships/add_sponsorship_without_sending_mail', to: "sponsorships#add_sponsorship_without_sending_mail", as: 'add_sponsorship_without_sending_mail'

  post '/home_requests/archive/:id', to: "home_requests#archive", as: "archive_home_request"
  post '/home_offers/archive/:id', to: "home_offers#archive", as: "archive_home_offer"
  get '/home_offers/matches_for_home_offer', to: "home_offers#matches_for_home_offer", as: "matches_for_home_offer"
  get '/home_offers/compare/:home_offer_id/:home_request_id', to: "home_offers#compare", as: "home_offers_compare"
  get '/home_requests/compare/:home_request_id/:home_offer_id', to: "home_requests#compare", as: "home_requests_compare"

  #search
  get 'animals/search_animals', to: 'animals#search_animals', as: 'search_animals'
  get 'home_offers/search_home_offers', to: 'home_offers#search_home_offers', as: 'search_home_offers'
  get 'home_requests/search_home_requests', to: 'home_requests#search_home_requests', as: 'search_home_requests'
  get 'sponsorships/search_sponsorships', to: 'sponsorships#search_sponsorships', as: 'search_sponsorships'

  #animals
  get 'animals/animal_in_need_of_sponsorship', to: 'animals#animal_in_need_of_sponsorship', as: 'animal_in_need_of_sponsorship'

  #admin
  get 'admin/visits', to: 'admin#visits', as: "visits"
  get 'admin/user_overview', to: 'admin#user_overview', as: "user_overview"
  post '/admin/create_user', to: 'admin#create_user', as: "create_user"
  delete '/admin/delete_user/:user_id', to: 'admin#delete_user', as: "delete_user"

  #offerer
  get '/offerers/process_to_create_home_offer', to: 'offerers#process_to_create_home_offer', as: "process_to_create_home_offer"
  post '/add_offerer', to: "offerers#add_offerer", as: 'add_offerer'

  #home_offer
  post 'home_offers/add_home_offer_to_offerer', to: "home_offers#add_home_offer_to_offerer", as: 'add_home_offer_to_offerer'

  #chicken_adoptions
  get 'chicken_adoptions/search_chicken_adoptions', to: 'chicken_adoptions#search_chicken_adoptions', as: 'search_chicken_adoptions'
  post '/chicken_adoptions/archive/:id', to: "chicken_adoptions#archive", as: "archive_chicken_adoption"

  #redirects
  #get '/team', to: redirect('/team_members')

  #newsletters
  post '/newsletters/add_newsletter_to_list', to: "newsletters#add_newsletter_to_list", as: "add_newsletter_to_list"

  #download custom files
  get "/download_vermittlungsbedingungen", to: 'home_requests#download_vermittlungsbedingungen', as: 'download_vermittlungsbedingungen'


  devise_for :users
  localized do
    resources :team_members
    resources :posts
    resources :home_requests
    resources :home_offers
    resources :animals
    resources :works
    resources :sponsorships
    resources :offerers
    resources :chicken_adoptions
    resources :newsletters
    resources :events
    resources :pages
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_comparison_home_offer_home_request.html.erb
<% comparison = RequestOfferComparison.new.compare(home_request, home_offer) %>
<%#= RequestOfferComparison.new.find_matches_for_offer(home_offer).count %>
<table class="table table-bordered text-center">
  <thead>
    <tr>
      <th scope="col">Attribut</th>
      <th scope="col"><%= HomeOffer.model_name.human %></th>
      <th scope="col"><%= HomeRequest.model_name.human %></th>
    </tr>
  </thead>
  <tbody>
    <% comparison[0].each do |c| %>
    <tr class="<%= c[3] %>">
      <td>
        <%= c[0] %>
      </td>
      <td>
        <%= c[2] %>
      </td>
      <td>
        <%= c[1] %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_comparison_home_request_home_offer.html.erb
<% comparison = RequestOfferComparison.new.compare(home_request, home_offer) %>
<%#= RequestOfferComparison.new.find_matches_for_offer(home_offer).count %>
<table class="table table-bordered text-center">
  <thead>
    <tr>
      <th scope="col">Attribut</th>
      <th scope="col"><%= HomeRequest.model_name.human %></th>
      <th scope="col"><%= HomeOffer.model_name.human %></th>
    </tr>
  </thead>
  <tbody>
    <% comparison[0].each do |c| %>
    <tr class="<%= c[3] %>">
      <td>
        <%= c[0] %>
      </td>
      <td>
        <%= c[1] %>
      </td>
      <td>
        <%= c[2] %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/shared/_general_information.html.erb
<div class="bg-light py-5">
  <div class="container">
    <div class="row my-5">
        <div class="col-12 col-lg-8">
          <% if is_current_user_admin? %>
            <div class="text-center">
              <%= link_to 'Neuer Eintrag', new_post_path, class: "btn btn-primary" %>
            </div><hr />
          <% end %>
          <h3 class="text-darker-base-color">Aktuell</h3>
          <p>
              <%= link_to ">> Alle Nachrichten anzeigen", posts_path %>
          </p>
          <%= render partial: "posts/side_image_show", collection: Post.all.order("created_at").reverse_order.first(5), as: :post %>
        </div>
        <div class="col-12 col-lg-4">
          <% if is_current_user_admin? %>
            <div class="text-center">
              <%= link_to 'Neuer Eintrag', new_event_path, class: "btn btn-primary" %>
            </div><hr />
          <% end %>
          <h3 class="text-darker-base-color">Kommende Events</h3>
          <p>
            <%= link_to ">> Alle Events anzeigen", events_path %>
          </p>
          <% events = Event.where("start > ?", DateTime.now).order("start") %>
          <%= render partial: "events/side_image_show", collection: events, as: :event %>
          <% if events.empty? %>
            <p>
              Zurzeit gibt es keine kommenden Events.
            </p>
            <p>
              Abonnieren Sie unseren Newsletter, um auf dem Laufenden zu bleiben!
            </p>
            <p>
              -> Newsletter
            </p>
          <% end %>

          <h3 class="text-darker-base-color">Praktikum</h3>
          <div class="card mb-3">
            <div class="row no-gutters">
              <div class="col-4">
                <%= link_to internship_path, class: "text-dark" do %>
                  <%= image_tag "annemarie-woehler.jpg", class: "card-img" %>
                <% end %>
              </div>
              <div class="col-8">
                <div class="card-body">
                  <strong><%= link_to "Freier Praktikumsplatz bei Stinah", internship_path, class: "text-dark" %></strong>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>

app/views/shared/_image_with_overlay_and_zoom.html.erb
<div class="card">
  <div class="hovereffect">
      <%= image_tag image, class: "card-img" %>
      <div class="card-img-overlay d-flex align-items-end">
        <h3 class="card-title text-white"><%= title %></h3>
      </div>
      <div class="overlay">
         <h2><%= post.title %></h2>
         <%= link_to "Lesen!", post_path(post), class: "info" %>
      </div>
  </div>
</div>

app/views/shared/_news_images.html.erb
  <%= render partial: "posts/card_with_overlay", post: Post.first %>

app/views/shared/_old_carousel.html.erb
<div class="row">
  <div class="col-2 d-flex align-items-center justify-content-center">
    <button type="button" class="carousel-prev btn btn-secondary btn-lg"> &#8249; </button>
  </div>
  <div class="col-8">
    <div id="carouselExampleControls" class="carousel slide mx-auto" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="https://loremflickr.com/600/300/animal?random=#1" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="https://loremflickr.com/600/300/animal?random=#2" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
          <img src="https://loremflickr.com/400/200/animal?random=#3" class="d-block w-100" alt="...">
        </div>
      </div>
    </div>
  </div>
  <div class="col-2 d-flex align-items-center justify-content-center">
      <button type="button" class="carousel-next btn btn-secondary btn-lg"> &#8250; </button>
  </div>
</div>

<script>
  $( document ).ready(function() {

    $( ".carousel-prev" ).click(function() {
      $('.carousel').carousel('prev');
    });

    $( ".carousel-next" ).click(function() {
      $('.carousel').carousel('next');
    });

    $('.carousel').carousel({
      interval: 3000
    });
  });
</script>

app/views/shared/_simple_gallery.html.erb
<hr />
<div class="row">
  <% images.each do |image| %>
    <div class="col-sm-12 col-md-6 col-lg-4 justify-content-center d-flex align-items-center mb-3">
      <%= image_tag image, class: "img-fluid rounded" %>
    </div>
  <% end %>
</div>

app/views/shared/_social_media_buttons.html.erb
<div id="<%= random_id %>">

</div>

<script>
  $( document ).ready(function() {
    $("#<%= random_id %>").jsSocials({
      showLabel: false,
      showCount: false,
      shares: ["facebook", "twitter", "email"],
      url: "<%= url %>",
      text: "<%= text %>",
    });
  });
</script>

app/views/shared/_thumbnail_carousel.html.erb
  <!-- Generate random token -->
  <% random_id = SecureRandom.hex(10) %>

  <!--Carousel Wrapper-->
  <div id="<%= random_id %>" class="carousel slide carousel-fade carousel-thumbnails" data-ride="carousel">
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
      <% images.each_with_index do |image, i| %>
        <div class="carousel-item <%= "active" if i == 0 %>">
          <%= image_tag image, class: "d-block w-100" %>
        </div>
      <% end %>
    </div>
    <div class="carousel-outer">
      <ol class="carousel-indicators">
        <li data-target="#<%= random_id %>" data-slide-to="0" class="active"></li>
        <% (images.size-1).times do |i| %>
            <li data-target="#<%= random_id %>" data-slide-to="<%= i + 1 %>"></li>
        <% end %>
      </ol>
    </div>
    <!--/.Slides-->
    <!--Controls-->
    <a class="carousel-control-prev" href="#<%= random_id %>" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#<%= random_id %>" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
  </div>
  <!--/.Carousel Wrapper-->
  <script>
    $( document ).ready(function() {

    });
  </script>

app/views/shared/_thumbnail_carousel_old.html.erb
  <!-- Generate random token -->
  <% random_id = SecureRandom.hex(10) %>

  <!--Carousel Wrapper-->
  <div id="<%= random_id %>" class="carousel slide carousel-fade carousel-thumbnails" data-ride="carousel">
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
      <% images.each_with_index do |image, i| %>
        <div class="carousel-item <%= "active" if i == 0 %>">
          <%= image_tag image, class: "d-block w-100" %>
        </div>
      <% end %>
    </div>
    <div class="carousel-outer">
      <ol class="carousel-indicators">
        <li data-target="#<%= random_id %>" data-slide-to="0" class="active"></li>
        <% (images.size-1).times do |i| %>
            <li data-target="#<%= random_id %>" data-slide-to="<%= i + 1 %>"></li>
        <% end %>
      </ol>
    </div>
    <!--/.Slides-->
    <!--Controls-->
    <a class="carousel-control-prev" href="#<%= random_id %>" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#<%= random_id %>" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
  </div>
  <!--/.Carousel Wrapper-->
  <script>
    $( document ).ready(function() {

    });
  </script>

app/views/shared/_welcome_thumbnail_carousel.html.erb
  <!--Carousel Wrapper-->
  <div id="carousel-thumb" class="carousel slide carousel-fade carousel-thumbnails" data-ride="carousel">
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
      <% image_names.each_with_index do |image_name, i| %>
        <div class="carousel-item <%= 'active' if i == 0 %>">
          <%= image_tag(image_name, class: "d-block w-100") %>
        </div>
      <% end %>
    </div>
    <div class="carousel-outer">
      <ol class="carousel-indicators">
        <% image_names.each_with_index do |image_name, i| %>
        <li data-target="#carousel-thumb" data-slide-to="<%= i %>" class="<%= 'active' if i == 0 %>"></li>
        <% end %>
      </ol>
    </div>
    <!--/.Slides-->
    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-thumb" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-thumb" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
  </div>
  <!--/.Carousel Wrapper-->
  <script>
    $( document ).ready(function() {

      $('#carousel-thumb').carousel({
        interval: 8000
      });
    });
  </script>

app/views/shared/_welcome_thumbnail_carousel_save.html.erb
  <!--Carousel Wrapper-->
  <div id="carousel-thumb" class="carousel slide carousel-fade carousel-thumbnails" data-ride="carousel">
    <!--Slides-->
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <%= image_tag("chicken.png", class: "d-block w-100") %>
      </div>
      <div class="carousel-item">
        <%= image_tag("goat.png", class: "d-block w-100") %>
      </div>
      <div class="carousel-item">
        <%= image_tag("pig.jpg", class: "d-block w-100") %>
      </div>
    </div>
    <div class="carousel-outer">
      <ol class="carousel-indicators">
        <li data-target="#carousel-thumb" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-thumb" data-slide-to="1"></li>
        <li data-target="#carousel-thumb" data-slide-to="2"></li>
      </ol>
    </div>
    <!--/.Slides-->
    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-thumb" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-thumb" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->
  </div>
  <!--/.Carousel Wrapper-->
  <script>
    $( document ).ready(function() {

      $('#carousel-thumb').carousel({
        interval: 2000
      });
    });
  </script>