config/routes.rb
Rails.application.routes.draw do


  resources :emergencies
  resources :testimonials
  root 'static_pages#welcome'

  localized do
    get 'calendar/(:date)', to: 'calendar#work_calendar', as: "work_calendar"
    get 'work_day_calendar/(:date)', to: 'calendar#work_day_calendar', as: "work_day_calendar"
    get '/newhome', to: 'static_pages#newhome', as: "newhome"
    get '/about', to: 'static_pages#about', as: "about"
    get '/faq', to: 'static_pages#faq', as: "faq"
    get '/contact', to: 'static_pages#contact', as: "contact"


    get '/internship', to: 'static_pages#internship', as: "internship"
    # get '/testimonials', to: 'static_pages#testimonials', as: "testimonials"
    get '/support', to: 'static_pages#support', as: "support"
    get '/privacy_statement', to: 'static_pages#privacy_statement', as: "privacy_statement"


    #get '/contact', to: 'pages#show', as: "contact", id: "kontakt"
    #get '/support', to: 'pages#show', as: "support", id: "unterstuetzen"
  end

  #save_the_chicken
  localized do
    scope "/save_the_chicken" do
      get '/', to: 'save_the_chicken#welcome', as: "save_the_chicken"
      get '/faq', to: 'save_the_chicken#faq', as: "save_the_chicken_faq"
      get '/contact', to: 'save_the_chicken#contact', as: "save_the_chicken_contact"
      get '/keeping', to: 'save_the_chicken#keeping', as: "save_the_chicken_keeping"
      get '/act_sustainable', to: 'save_the_chicken#act_sustainable', as: "save_the_chicken_act_sustainable"
      get '/new_home', to: 'save_the_chicken#new_home', as: "save_the_chicken_new_home"
      get '/donation', to: 'save_the_chicken#donation', as: "save_the_chicken_donation"
      get '/picture_gallery', to: 'save_the_chicken#picture_gallery', as: "save_the_chicken_picture_gallery"
      get '/requirements', to: 'save_the_chicken#requirements', as: "save_the_chicken_requirements"
    end
  end

  post '/save_the_chicken/create_for_adopters', to: "chicken_adoptions#create_for_adopters", as: "create_for_adopters"
  get '/save_the_chicken/successfully_added_chicken_adoption', to: "chicken_adoptions#successfully_added_chicken_adoption", as: "successfully_added_chicken_adoption"

  get 'home_offers/successfully_added_home_offer', to: 'home_offers#successfully_added_home_offer', as: "successfully_added_home_offer"
  get 'home_requests/successfully_added_home_request', to: 'home_requests#successfully_added_home_request', as: "successfully_added_home_request"

  get '/impressum', to: 'static_pages#impressum', as: "impressum"
  get '/cookies', to: 'static_pages#cookies', as: "cookies"

  post '/works/create_for_calendar/', to: "works#create_for_calendar", as: 'create_for_calendar'
  delete '/works/delete_for_calendar/:id', to: "works#delete_for_calendar", as: 'delete_for_calendar'

  #sponsorship
  get '/sponsorships/my_sponsorships', to: "sponsorships#my_sponsorships", as: 'my_sponsorships'
  post '/sponsorships/add_sponsorship', to: "sponsorships#add_sponsorship", as: 'add_sponsorship'
  post '/sponsorships/add_sponsorship_with_new_user', to: "sponsorships#add_sponsorship_with_new_user", as: 'add_sponsorship_with_new_user'
  get '/sponsorships/activate_sponsorship/:id', to: "sponsorships#activate_sponsorship", as: 'activate_sponsorship'
  get '/sponsorships/deactivate_sponsorship/:id', to: "sponsorships#deactivate_sponsorship", as: 'deactivate_sponsorship'
  post '/sponsorships/check_payment/:id', to: "sponsorships#check_payment", as: 'check_payment'
  post '/sponsorships/add_sponsorship_without_sending_mail', to: "sponsorships#add_sponsorship_without_sending_mail", as: 'add_sponsorship_without_sending_mail'

  post '/home_requests/archive/:id', to: "home_requests#archive", as: "archive_home_request"
  post '/home_offers/archive/:id', to: "home_offers#archive", as: "archive_home_offer"
  get '/home_offers/matches_for_home_offer', to: "home_offers#matches_for_home_offer", as: "matches_for_home_offer"
  get '/home_offers/compare/:home_offer_id/:home_request_id', to: "home_offers#compare", as: "home_offers_compare"
  get '/home_requests/compare/:home_request_id/:home_offer_id', to: "home_requests#compare", as: "home_requests_compare"

  #search
  get 'animals/search_animals', to: 'animals#search_animals', as: 'search_animals'
  get 'home_offers/search_home_offers', to: 'home_offers#search_home_offers', as: 'search_home_offers'
  get 'home_requests/search_home_requests', to: 'home_requests#search_home_requests', as: 'search_home_requests'
  get 'sponsorships/search_sponsorships', to: 'sponsorships#search_sponsorships', as: 'search_sponsorships'

  #animals
  get 'animals/animal_in_need_of_sponsorship', to: 'animals#animal_in_need_of_sponsorship', as: 'animal_in_need_of_sponsorship'

  #admin
  get 'admin/visits', to: 'admin#visits', as: "visits"
  get 'admin/user_overview', to: 'admin#user_overview', as: "user_overview"
  post '/admin/create_user', to: 'admin#create_user', as: "create_user"
  delete '/admin/delete_user/:user_id', to: 'admin#delete_user', as: "delete_user"

  #offerer
  get '/offerers/process_to_create_home_offer', to: 'offerers#process_to_create_home_offer', as: "process_to_create_home_offer"
  post '/add_offerer', to: "offerers#add_offerer", as: 'add_offerer'

  #home_offer
  post 'home_offers/add_home_offer_to_offerer', to: "home_offers#add_home_offer_to_offerer", as: 'add_home_offer_to_offerer'

  #chicken_adoptions
  get 'chicken_adoptions/search_chicken_adoptions', to: 'chicken_adoptions#search_chicken_adoptions', as: 'search_chicken_adoptions'
  post '/chicken_adoptions/archive/:id', to: "chicken_adoptions#archive", as: "archive_chicken_adoption"

  #redirects
  #get '/team', to: redirect('/team_members')

  #newsletters
  post '/newsletters/add_newsletter_to_list', to: "newsletters#add_newsletter_to_list", as: "add_newsletter_to_list"

  #download custom files
  get "/download_vermittlungsbedingungen", to: 'home_requests#download_vermittlungsbedingungen', as: 'download_vermittlungsbedingungen'


  devise_for :users
  localized do
    resources :team_members
    resources :posts
    resources :home_requests
    resources :home_offers
    resources :animals
    resources :works
    resources :sponsorships
    resources :offerers
    resources :chicken_adoptions
    resources :newsletters
    resources :events
    resources :pages
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/offerer.rb
class Offerer < ApplicationRecord

  validates :firstname, :lastname, :street, :plz, :city,
            :phone, :email, :year, :experience,
            :motivation, :plans,:privacy_statement, presence: true

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }

  has_many :home_offers
  accepts_nested_attributes_for :home_offers, reject_if: :all_blank

  scope :offerers_ilike, ->(search_term) { where("search_field ILIKE ?", search_term) }

  def name
    "#{firstname} #{lastname}"
  end

    before_save :update_search_field

  def update_search_field

    # Offerer.find_each(&:save)

    self.search_field =
    [
      firstname,
      lastname,
      street,
      plz,
      city,
      phone,
      email,
      year,
      experience,
      motivation,
      plans
    ].compact.join(' ')

  end
end

app/controllers/offerers_controller.rb
class OfferersController < ApplicationController
  before_action :set_offerer, only: [:show, :edit, :update, :destroy]

  # GET /offerers
  # GET /offerers.json
  def index
    @offerers = Offerer.all
  end

  # GET /offerers/1
  # GET /offerers/1.json
  def show
  end

  # GET /offerers/new
  def new
    @offerer = Offerer.new
    #@offerer.home_offers.build
  end

  # GET /offerers/1/edit
  def edit

  end

  def process_to_create_home_offer
    @offerer = Offerer.new
  end

  def add_offerer
    @offerer = Offerer.new(offerer_params)
    respond_to do |format|
      if @offerer.save
        flash[:notice] = "Angaben wurde eingetragen!"
        format.js #{ redirect_to offerer_path(@offerer) }
        #format.html { redirect_to offerer_path(@offerer) }
      else
        format.js
        #format.html { render :process_to_create_home_offer }
      end
    end
  end

  # POST /offerers
  # POST /offerers.json
  def create
    @offerer = Offerer.new(offerer_params)
    #byebug

    respond_to do |format|
      if @offerer.save
        format.html { redirect_to @offerer, notice: 'Offerer was successfully created.' }
        format.json { render :show, status: :created, location: @offerer }
      else
        format.html { render :new }
        format.json { render json: @offerer.errors, status: :unprocessable_entity }
      end
    end
    #byebug
  end

  # PATCH/PUT /offerers/1
  # PATCH/PUT /offerers/1.json
  def update
    respond_to do |format|
      if @offerer.update(offerer_params)
        format.html { redirect_to @offerer, notice: 'Offerer was successfully updated.' }
        format.json { render :show, status: :ok, location: @offerer }
      else
        format.html { render :edit }
        format.json { render json: @offerer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offerers/1
  # DELETE /offerers/1.json
  def destroy
    @offerer.destroy
    respond_to do |format|
      format.html { redirect_to offerers_url, notice: 'Offerer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offerer
      @offerer = Offerer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offerer_params
      params.require(:offerer).permit(:firstname, :lastname, :street, :city, :plz, :phone, :email, :year, :experience, :motivation, :plans, :privacy_statement, home_offers_attributes: [:id, :species, :race, :age, :min_age, :max_age, :size, :min_size, :max_size, :gender, :castrated, :rideable, :stable, :stable_alt, :from_then_on])
    end
end

app/helpers/offerers_helper.rb
module OfferersHelper
end

app/views/offerers/_form.html.erb
<%= simple_form_for(@offerer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <h4>Angaben zur Person</h4>
    <hr />
      <div class="row">
        <div class="col-12">
            <p>
              Name *
            </p>
        </div>
        <div class="col-6">
          <%= f.input :firstname, label: false, placeholder: "Vorname", required: true %>
        </div>
        <div class="col-6">
          <%= f.input :lastname, label: false, placeholder: "Nachname", required: true %>
        </div>
        <div class="col-12">
          <hr />
            Adresse *
        </div>
        <div class="col-12">
          <p>
            <%= f.input :street, label: false, placeholder: "Hauptstrasse 5" %>
          </p>
        </div>
        <div class="col-6">
          <%= f.input :city, label: false, placeholder: "Zürich", required: true  %>
        </div>
        <div class="col-6">
          <%= f.input :plz, label: false, placeholder: "8000", required: true  %>
        </div>
      </div>
      <hr />
    <%= f.input :phone, placeholder: "0791234567", required: true %>
    <%= f.input :email, placeholder: "beispiel@email.com", required: true %>
    <%= f.input :year, placeholder: '1988', required: true %>
    <hr />
    <h4>Angaben zur Erfahrung und Motivation</h4>
    <hr />
    <%= f.input :experience, placeholder: 'z.B. Ausbildung als Pferdefachfrau', required: true %>
    <%= f.input :motivation, placeholder: '', required: true  %>
    <%= f.input :plans, placeholder: '', required: true %>
    <hr />
    <%= f.input :privacy_statement, label: "Ich bin mit der #{link_to 'Datenschutzerklärung', privacy_statement_path, target: '_blank'} einverstanden".html_safe, required: true %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/offerers/_form_for_process_to_create_home_offer.html.erb
<div class="jumbotron">
  <%= simple_form_for(offerer, url: add_offerer_path, method: :post, remote: true) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <h4>Angaben zur Person</h4>
      <hr />
        <div class="row">
          <div class="col-12">
              <p>
                Name *
              </p>
          </div>
          <div class="col-6">
            <%= f.input :firstname, label: false, placeholder: "Vorname", required: true %>
          </div>
          <div class="col-6">
            <%= f.input :lastname, label: false, placeholder: "Nachname", required: true %>
          </div>
          <div class="col-12">
            <hr />
              Adresse *
          </div>
          <div class="col-12">
            <p>
              <%= f.input :street, label: false, placeholder: "Hauptstrasse 5" %>
            </p>
          </div>
          <div class="col-6">
            <%= f.input :city, label: false, placeholder: "Zürich", required: true  %>
          </div>
          <div class="col-6">
            <%= f.input :plz, label: false, placeholder: "8000", required: true  %>
          </div>
        </div>
        <hr />
      <%= f.input :phone, placeholder: "0791234567", required: true %>
      <%= f.input :email, placeholder: "beispiel@email.com", required: true %>
      <%= f.input :year, placeholder: '1988', required: true %>
      <hr />
      <h4>Angaben zur Erfahrung und Motivation</h4>
      <hr />
      <%= f.input :experience, placeholder: 'z.B. Ausbildung als Pferdefachfrau', required: true %>
      <%= f.input :motivation, placeholder: '', required: true  %>
      <%= f.input :plans, placeholder: '', required: true %>
      <hr />
      <%= f.input :privacy_statement, label: "Ich bin mit der #{link_to 'Datenschutzerklärung', privacy_statement_path, target: '_blank'} einverstanden".html_safe, required: true %>

    </div>

    <div class="form-actions">
      <%= f.button :submit, "Weiter", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/offerers/_home_offer.html.erb
<% home_offer = f.object %>

<div id="<%= "offerer_home_offers_attributes_#{f.index}" %>" class="border rounded p-2 my-4">
  <h4>Angaben zum gewünschten Tier</h4>
  <hr />
  <%= f.input :species, collection: Animal.species.map {|p| [t("#{p}", count: 1), p]}, required: true %>
  <%= f.input :race, placeholder: 'z.B. "Araber" oder "egal"', required: true %>

  <div class="form-inline pb-3">
      <span class="pr-3">Alter: *</span>
      <%= f.input :age, label: "egal" %>
  </div>

  <div class="row">
    <div class="col-6">
      <%= f.input :min_age, input_html: {  value: home_offer.min_age || 0 }, required: true, readonly: home_offer.age %>
    </div>
    <div class="col-6">
      <%= f.input :max_age, input_html: {  value: home_offer.max_age || 100 }, required: true, readonly: home_offer.age %>
    </div>
  </div>
  <div class="form-inline pb-3">
      <span class="pr-3">Grösse: *</span>
      <%= f.input :size, label: " egal" %>
  </div>

  <div class="row">
    <div class="col-6">
      <%= f.input :min_size, input_html: {  value: home_offer.min_size || 0 }, required: true, readonly: home_offer.size %>
    </div>
    <div class="col-6">
      <%= f.input :max_size, input_html: {  value: home_offer.max_size || 300 }, required: true, readonly: home_offer.size %>
    </div>
  </div>

  <%= f.input :gender, collection: Animal.genders.map {|p| [t("#{p}"), p]}, selected: :whatever, required: true %>
  <%= f.input :castrated, collection: Animal.castrated.map {|p| [t("#{p}"), p]}, selected: :whatever, required: true %>
  <%= f.input :rideable %>
  <hr />
  <h4>Angaben zum angebotenen Platz</h4>
  <hr />
  <%= f.input :stable, collection: Animal.stables.map {|p| [p, p]}, required: true %>

  <div id="<%= "offerer_home_offers_attributes_#{f.index}" %>_stable_alt_field" class="<%= 'hidden' if home_offer.stable != 'Anderes' %>">
    <%= f.input :stable_alt %>
  </div>
  <%= f.input :from_then_on, required: true %>

  <button id="<%= "offerer_home_offers_attributes_#{f.index}" %>_add" type="button" class="btn btn-primary"><%= fa_icon "plus" %> Weiteres Wunsch-Tier hinzufügen</button>

  <script>
    $( document ).ready(function() {

      let f_index = "<%= f.index %>";
      let form_id = "#offerer_home_offers_attributes_" + f_index;
      var home_offer_changed = "<%= (f.index == 0 || !home_offer.empty?).to_s %>";

      if(home_offer_changed === "false"){
        $(form_id + " :input").prop("disabled", true);
        $(form_id).hide();
      }

      $( form_id + "_add" ).click(function() {
        var f_index_next = parseInt(f_index) + 1;
        var form_id_next = "#offerer_home_offers_attributes_" + f_index_next;
        $(form_id_next + " :input").prop("disabled", false);
        $(form_id_next).show();
        $(this).hide();
      });

      $(form_id + "_age").change(function(){
        if ($(form_id + "_age").is(':checked')) {
          $(form_id + "_min_age").prop("readonly", true);
          $(form_id + "_max_age").prop("readonly", true);
          $(form_id + "_min_age").val(0);
          $(form_id + "_max_age").val(100);
        } else {
          $(form_id + "_min_age").prop("readonly", false);
          $(form_id + "_max_age").prop("readonly", false);
        }
      });

      $(form_id + "_size").change(function(){
        if ($(form_id + "_size").is(':checked')) {
          $(form_id + "_min_size").prop("readonly", true);
          $(form_id + "_max_size").prop("readonly", true);
          $(form_id + "_min_size").val(0);
          $(form_id + "_max_size").val(300);
        } else {
          $(form_id + "_min_size").prop("readonly", false);
          $(form_id + "_max_size").prop("readonly", false);
        }
      });

      $(form_id + "_stable").change(function(){
        if ($(this).val().toLowerCase() === "anderes") {
          $(form_id + "_stable_alt_field").toggle();
        } else {
          $(form_id + "_stable_alt_field").hide();
        }
      });

    });
  </script>

</div>

app/views/offerers/_show.html.erb
<div class="jumbotron bg-white text-justify text-darker-base-color">
  <h2 class="text-center">Ich möchte folgende Tiere aufnehmen</h2>
  <p>
    Mit dem Formular unten können Sie angeben, welche Tiere Sie aufnehmen möchten.
  </p>
  <p>
    <strong>Sie können mehrere Tiere eintragen!</strong>
  </p>

  <div class="jumbotron">
    <%= render 'home_offers/form_for_offerer', home_offer: HomeOffer.new, offerer: offerer %>
  </div>

  <% offerer.home_offers.each_with_index do |home_offer, i| %>
    <div class="card my-3">
      <div class="card-body text-justify">
          <h4>Tier <%= i + 1 %></h4>
          <hr />
          <b><%= home_offer.class.human_attribute_name("species") %></b>: <%= t(home_offer.species, count: 1) %>
          <br />
          <b><%= home_offer.class.human_attribute_name("race") %></b>: <%= t(home_offer.race) %>
          <br />
          <b>Alter (in Jahren)</b>: <%= home_offer.min_age %> - <%= home_offer.max_age %>
          <br />
          <b>Grösse (in Centimeter)</b>: <%= home_offer.min_size %> - <%= home_offer.max_size %>
          <br />
          <b><%= home_offer.class.human_attribute_name("gender") %></b>: <%= t(home_offer.gender) %>
          <br />
          <b><%= home_offer.class.human_attribute_name("castrated") %></b>: <%= t(home_offer.castrated) %>
          <br />
          <br />
      </div>
    </div>
  <% end %>

  <div class="card my-3 <%= dom_id(offerer) %>">
    <div class="card-body">
      <div class="text-justify">
        <h4>Angaben zur Person</h4>
        <hr />
        <p>
          <%= offerer.name %>
          <br />
          <%= offerer.street %>
          <br />
          <%= offerer.city %> <%= offerer.plz %>
          <br />
          <%= offerer.phone %>
          <br />
          <%= mail_to offerer.email %>
        </p>
        <hr />
        <h4>Angaben zur Erfahrung und Motivation</h4>
        <hr />
        <p>
          <b><%= offerer.class.human_attribute_name("experience") %></b> <br />
          <%= offerer.experience %>
        </p>
        <p>
          <b><%= offerer.class.human_attribute_name("motivation") %></b> <br />
          <%= offerer.motivation %>
        </p>
        <p>
          <b><%= offerer.class.human_attribute_name("plans") %></b> <br />
          <%= offerer.plans %>
        </p>
      </div>


    </div>
  </div>

</div>

app/views/offerers/add_offerer.js.erb
var record_id = "#process_to_create_home_offer";
var errors = <%= raw @offerer.errors.full_messages %>;

if (jQuery.isEmptyObject(errors)) {
  console.log("keine Fehler");

  window.location.href = "<%= offerer_path(@offerer) %>";

  content = $("<%= escape_javascript( render 'offerers/show', offerer: @offerer ) %>");
  $(record_id).fadeOut("fast", function(){
    $(record_id).empty().append(content).fadeIn("fast");
  });

} else {
  console.log("Fehler vorhanden");

    content = $("<%= escape_javascript( render 'offerers/form_for_process_to_create_home_offer', offerer: @offerer ) %>");
    $(record_id).fadeOut("fast", function(){
      $(record_id).empty().append(content).fadeIn("fast");
    });

}

app/views/offerers/edit.html.erb
<div class="container">
  <div class="jumbotron bg-white">
    <%= render 'form', offerer: @offerer %>
  </div>
</div>

app/views/offerers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Offerers</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Street</th>
      <th>City</th>
      <th>Plz</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Year</th>
      <th>Experience</th>
      <th>Motivation</th>
      <th>Plans</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offerers.each do |offerer| %>
      <tr>
        <td><%= offerer.firstname %></td>
        <td><%= offerer.lastname %></td>
        <td><%= offerer.street %></td>
        <td><%= offerer.city %></td>
        <td><%= offerer.plz %></td>
        <td><%= offerer.phone %></td>
        <td><%= offerer.email %></td>
        <td><%= offerer.year %></td>
        <td><%= offerer.experience %></td>
        <td><%= offerer.motivation %></td>
        <td><%= offerer.plans %></td>
        <td><%= link_to 'Show', offerer %></td>
        <td><%= link_to 'Edit', edit_offerer_path(offerer) %></td>
        <td><%= link_to 'Destroy', offerer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Offerer', new_offerer_path %>

app/views/offerers/new.html.erb
<div class="container">
  <div class="jumbotron bg-white">
    <%= render 'form', offerer: @offerer %>
  </div>
</div>

app/views/offerers/process_to_create_home_offer.html.erb
<div class="container">
  <div class="jumbotron bg-white text-justify text-darker-base-color">
      <h2 class="text-center">Ich biete einem Tier ein neues Zuhause</h2>
      <p>
        Herzlichen Dank, dass Sie einem Tier in schwieriger Situation helfen wollen. Der Verzicht darauf, die Tierproduktion durch die eigene Nachfrage bei Produzenten anzukurbeln, ist der effizienteste Beitrag zur Vermeidung von Tierleid und die Aufnahme eines betroffenen Individuums an einen wohlumsorgten Platz bedeutet für dieses vielfach Leben.
      </p>
      <p>
        Bitte beachten Sie, dass die Stiftung für die Gesundheit, eine bestimmte Eigenschaft eines Tieres bzw. deren Fehlen keine Gewährleistung übernehmen kann.
      </p>
      <p>
        Tiere, die aus dem Eigentum der Stiftung - also nicht direkt über die Kontaktherstellung - gegen Schutzgebühr zur Pflege platziert werden, sind tierärztlich versorgt. Interessieren Sie sich für ein solches Tier, so werden wir Sie über sämtliche uns bekannten Verhaltensbesonderheiten oder Krankengeschichten informiert und können sich auch nach der Übernahme des Tieres jederzeit mit Fragen an uns richten. Die Weiterbetreuung von aus der Stiftung vermittelten Tieren ist uns ein grosses Anliegen.
      </p>
      <p>
        <b>Sobald wir Ihr Formular erhalten haben, werden wir uns mit Ihnen in Verbindung setzen.</b>
      </p>
    <div id="process_to_create_home_offer">
      <%= render 'form_for_process_to_create_home_offer', offerer: @offerer %>
    </div>
  </div>
</div>

app/views/offerers/show.html.erb
<div class="container-fluid">
  <%= render 'show', offerer: @offerer %>
</div>